# ベースイメージの指定
FROM node:lts
# 作業ディレクトリの指定
WORKDIR /usr/src/app

# firebaseのインストール
RUN npm install firebase
RUN npm install -g firebase-tools

# # react-router-domのインストール
# RUN npm i -S react-router-dom 

# # chakra-uiのインストール
# RUN npm i  @chakra-ui/react @emotion/react @emotion/styled framer-motion